"use client";

import type { Metadata } from "next";
import "./styles/globals.css";
import "./styles/layout.css";
import Logo from "./assets/Logo";
import MenuBar from "./components/menuBar";
import { useState } from "react";
import Icon from "./components/Icon/Icon";
import { Space_Mono } from 'next/font/google'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceMono = Space_Mono({
  weight: '400',
  subsets: ['latin']
})

const RootLayout = ({ children }: { children: React.ReactNode }) => {

  return (
    <html lang="fr" className={spaceMono.className}>
      <body className='theme-app'>
        <div className="content-container">
          <div className="navigation-container">
            <div className="logo-container">
              <Icon>
                <Logo color={"#FFB800"} />
              </Icon>
            </div>
            <div className="menu-bar-container">
              <MenuBar />
            </div>
          </div>
          <div className="children-container">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
