"use client";

import type { Metadata } from "next";
import "./styles/globals.css";
import "./styles/layout.css";
import Logo from "./assets/Logo";
import MenuBar from "./components/menuBar";
import { useState } from "react";
import Icon from "./components/Icon/Icon";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const [isHover, setIsHover] = useState(false);

  return (
    <html lang="fr">
      <body className="theme-app">
        <div className="navigation-container">
          <div className="logo-container">
            <Icon handleMouseEnter={() => setIsHover(true)} handleMouseLeave={() => setIsHover(false)}>
              <Logo color={isHover ? "#FFB800" : "#FFFFFF"} />
            </Icon>
          </div>
          <div className="menu-bar-container">
            <MenuBar />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
